{
  "hash": "e82e5efb50a95c2d75770510e1cc011c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Reading Sydney's Water Quality\"\ndescription: \"A reproducible R exploration of swimming-site samples, monthly variation, and the importance of missing data.\"\nauthor: \"Aphiaut Imuan\"\ndate: \"2025-05-20\"\ncategories: [R, Environment, TidyTuesday]\nimage: \"water.jpg\"\nbody-classes: post-water\n---\n\nWater-quality data looks simple at first. There is a place, a date, and a measurement. But once I started exploring this dataset, I realised that the numbers were not quite as straightforward as they seemed.\n\nA high average, for example, does not necessarily mean that every sample from a site was high. It could be the result of just one unusually large measurement. Missing values also need some care: a measurement that was never recorded is very different from a recorded value of zero.\n\nIn this post, I use R to explore where samples were collected around Sydney, take a closer look at site measurements during April 2024, and then step back to see how the distribution has changed over time.\n\n## About the data\n\nThe data comes from the [TidyTuesday release of 20 May 2025](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-05-20), based on monitoring data from NSW Beachwatch.\n\nFor this exploration, I focus on **enterococci**, measured in colony-forming units per 100 mL (CFU / 100 mL).\n\nBefore doing any comparisons, I removed records without a valid date or enterococci measurement, as well as negative measurements. I kept genuine zero measurements, because zero is still an observed value.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lubridate)\nlibrary(sf)\n\nwater_quality <- read_csv(\"data/water_quality.csv\", show_col_types = FALSE) |>\n  mutate(date = as.Date(date))\n\ntheme_set(theme_minimal(base_size = 12) +\n  theme(panel.grid.minor = element_blank(),\n        plot.title = element_text(face = \"bold\", colour = \"#285d7b\"),\n        plot.background = element_rect(fill = \"#fbfdff\", colour = NA)))\n\nvalid <- water_quality |>\n  filter(!is.na(date), !is.na(enterococci_cfu_100ml),\n         enterococci_cfu_100ml >= 0)\n\ncoverage <- tibble(\n  Measure = c(\"Rows in source\", \"Rows with a valid date and non-negative measurement\",\n              \"Distinct council / site pairs\", \"First sample\", \"Last sample\"),\n  Value = c(nrow(water_quality), nrow(valid),\n            nrow(distinct(valid, council, swim_site)),\n            as.character(min(valid$date)), as.character(max(valid$date)))\n)\n#knitr::kable(coverage, caption = \"Coverage of the downloaded snapshot\")\n```\n:::\n\n\nThere are **123,530 rows** in the original dataset. After removing records without a usable date or measurement, **123,223 observations** remain. These represent **79 council–site combinations**, with samples stretching from September 1991 to April 2025.\n\nOne detail is especially important for the rest of the analysis: I leave missing measurements as missing. I do not turn them into zero. A zero means that a measurement was actually recorded as zero; a missing value means that there is no measurement to summarise.\n\nThis is historical monitoring data, so the results here describe the downloaded dataset rather than current swimming conditions.\n\n## Where were samples collected?\n\nBefore looking at the measurements themselves, I wanted to see where the observations actually came from.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsites <- water_quality |>\n  distinct(council, swim_site, latitude, longitude) |>\n  drop_na(latitude, longitude)\n\nload(\"data/lgas.rda\")\nlgas <- lgas %>% na.omit()\nnsw_map <- ggplot(lgas) +\n  geom_sf(fill=NA, colour=\"grey80\",fill = \"white\")\n\n\nnsw_map +\n  coord_sf(xlim = c(150, 151.5), ylim = c(-34.2, -33.4), expand = FALSE) + \n  geom_point(data=sites, aes(x=longitude,\n                                y=latitude, group=NA),\n             colour = \"#377ca0\", alpha = 0.65, size = 1.8) +\n  \n  labs(title = \"The geography of the samples\", x = \"Longitude\", y = \"Latitude\")\n```\n\n::: {.cell-output-display}\n![Sampling coordinates in the source data. This is a location plot, without a coastline basemap.](index_files/figure-html/fig-sites-1.png){#fig-sites fig-alt='Scatter plot of swimming-site longitude and latitude, showing the geographic coverage of monitoring locations.' width=768}\n:::\n:::\n\n\nThe sampling locations are clearly concentrated around Sydney's coast and harbour. There are also a handful of sites further inland, but the eastern side of the map contains most of the observations.\n\nThis is useful context for everything that follows. The dataset represents a network of monitored locations rather than every possible swimming site across Sydney. Areas without points on the map should therefore be read as places that are not represented here, not places where the water necessarily had lower measurements.\n\n**Figure 1.** Locations represented in the water-quality data. Most monitoring sites are concentrated around Sydney's coastline and harbour.\n\n## Which sites stood out in April 2024?\n\nWith more than three decades of data, comparing every site across the full time period would quickly become difficult to interpret. Instead, I picked **April 2024** as a snapshot and calculated the average enterococci measurement for each site during that month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril <- valid |>\n  filter(date >= as.Date(\"2024-04-01\"), date < as.Date(\"2024-05-01\")) |>\n  group_by(council, swim_site) |>\n  summarise(samples = n(), mean_cfu = mean(enterococci_cfu_100ml),\n            median_cfu = median(enterococci_cfu_100ml),\n            max_cfu = max(enterococci_cfu_100ml), .groups = \"drop\") |>\n  arrange(desc(mean_cfu))\nstopifnot(nrow(april) > 0)\ntop_sites <- april |>\n  slice_head(n = 15) |>\n  mutate(site_label = paste(swim_site, council, sep = \" · \"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(top_sites, aes(mean_cfu, reorder(site_label, mean_cfu))) +\n  geom_col(fill = \"#91c7da\", width = 0.7) +\n  geom_text(aes(label = paste0(\"n = \", samples)), hjust = -0.12, size = 3.2) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.18))) +\n  labs(title = \"A monthly snapshot, not a permanent ranking\",\n       x = \"Mean enterococci (CFU / 100 mL)\", y = NULL)\n```\n\n::: {.cell-output-display}\n![The 15 highest site means in April 2024. Labels show the number of valid samples contributing to each mean.](index_files/figure-html/fig-april-1.png){#fig-april fig-alt='Horizontal bar chart comparing mean enterococci measurements for 15 swimming sites, with sample counts beside the bars.' width=960}\n:::\n:::\n\n\nA few sites immediately stand out.\n\n**Bilarong Reserve** has the highest mean in this snapshot, at about **406 CFU / 100 mL**. **Queenscliff Beach** follows at roughly **235**, while **Tamarama Beach** and **Darling Harbour** also have noticeably higher means than most of the other sites shown.\n\nBut the small labels beside the bars are just as important as the bars themselves.\n\nMost of these averages are based on only **five or six samples**. That makes the chart useful for understanding what happened during April 2024, but it would be misleading to treat it as a permanent ranking of the sites.\n\nIt is better thought of as a snapshot: these are the sites with the highest recorded averages **during this particular month**.\n\n**Figure 2.** Sites with the highest mean enterococci measurements in April 2024. Each label shows how many valid samples contributed to the monthly average.\n\n## What is hiding behind the average?\n\nThe April chart raised another question for me.\n\nBilarong Reserve had a mean of 406. Does that mean its individual measurements were consistently around 400?\n\nNot quite.\n\nLooking at the mean alongside the median and maximum gives a much better picture of what happened within the month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril |>\n  slice_head(n = 10) |>\n  select(Council = council, Site = swim_site, Samples = samples,\n         Mean = mean_cfu, Median = median_cfu, Maximum = max_cfu) |>\n  knitr::kable(digits = 1, caption = \"Sample counts and distribution summaries for the ten highest means\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sample counts and distribution summaries for the ten highest means\n\n|Council                    |Site              | Samples|  Mean| Median| Maximum|\n|:--------------------------|:-----------------|-------:|-----:|------:|-------:|\n|Northern Beaches Council   |Bilarong Reserve  |       5| 406.0|  200.0|    1100|\n|Northern Beaches Council   |Queenscliff Beach |       5| 234.8|   30.0|     700|\n|Waverley Council           |Tamarama Beach    |       6| 174.8|   23.5|     960|\n|The City of Sydney         |Darling Harbour   |       6| 166.0|   70.0|     490|\n|Waverley Council           |Bronte Beach      |       6| 126.3|   11.5|     420|\n|Sutherland Shire Council   |Boat Harbour      |       6|  79.7|   60.0|     170|\n|Randwick City Council      |Little Bay Beach  |       6|  69.0|   31.0|     280|\n|Northern Beaches Council   |Clontarf Pool     |       6|  68.2|   22.0|     210|\n|Randwick City Council      |Coogee Beach      |       6|  65.8|   24.0|     220|\n|City of Canada Bay Council |Cabarita Beach    |       6|  63.8|   13.0|     320|\n\n\n:::\n:::\n\n\nFor **Bilarong Reserve**, the mean is **406**, but the median is **200** and the maximum reaches **1,100 CFU / 100 mL**.\n\nThe difference is even more striking at **Queenscliff Beach**. Its mean is about **235**, but its median is only **30**, while the highest measurement is **700**.\n\n**Tamarama Beach** tells a similar story: a mean of roughly **175**, a median of **23.5**, and a maximum of **960**.\n\nThese are very different descriptions of the same data.\n\nThe mean is being pulled upward by relatively large observations, while the median tells us that a typical sample during the month was much lower. That does not make the mean incorrect; it simply shows why I would not want to interpret it on its own.\n\nFor these sites, the **sample count, mean, median, and maximum together** tell a much more useful story than a single average.\n\n## Missing does not mean zero\n\nThere was another issue I had to think about while working with this dataset.\n\nEach swimming site belongs to a particular council. This means that many theoretical council–site combinations simply do not exist.\n\nIf I created a complete council-by-site grid and filled all of those empty combinations with zero, the resulting chart would look complete, but it would quietly introduce information that was never observed.\n\nA blank combination does not mean:\n\n> enterococci = 0\n\nIt means:\n\n> there is no observation for that combination.\n\nThat distinction is why I keep missing combinations as missing and compare the observed sites directly instead.\n\nIt is a small data-cleaning decision, but it changes the meaning of the result.\n\n## How have measurements varied over time?\n\nAfter looking closely at one month, I wanted to zoom back out.\n\nInstead of following individual sites, I summarised the recorded measurements within each month from 2000 onward. The dark line shows the **monthly median**, while the shaded area represents the **interquartile range**, or the middle 50% of observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly <- valid |>\n  filter(year(date) >= 2000) |>\n  mutate(month = floor_date(date, \"month\")) |>\n  group_by(month) |>\n  summarise(median_cfu = median(enterococci_cfu_100ml),\n            q25 = quantile(enterococci_cfu_100ml, 0.25),\n            q75 = quantile(enterococci_cfu_100ml, 0.75),\n            samples = n(), .groups = \"drop\")\n\nggplot(monthly, aes(month, median_cfu)) +\n  geom_ribbon(aes(ymin = q25, ymax = q75), fill = \"#c5e3ed\") +\n  geom_line(colour = \"#285d7b\", linewidth = 0.6) +\n  labs(title = \"The centre of the distribution — and its spread\",\n       x = NULL, y = \"Enterococci (CFU / 100 mL)\")\n```\n\n::: {.cell-output-display}\n![Median and interquartile range of recorded measurements within each month since 2000; changing site coverage can affect this pooled summary.](index_files/figure-html/fig-monthly-1.png){#fig-monthly fig-alt='Time-series chart with a monthly median line and a shaded interval from the 25th to 75th percentile.' width=864}\n:::\n:::\n\n\nMost of the time, the median stays relatively low. The spread around it, however, is much less consistent.\n\nSome months have a narrow band, meaning that the middle half of the observations were fairly similar. In other months, the band becomes much wider, showing that measurements varied considerably across the samples recorded during that period.\n\nThere is a particularly large spread near the beginning of the series, followed by smaller but still noticeable spikes throughout later years.\n\nI would be careful about reading this as a simple story of water quality getting better or worse over time. The monitoring network itself may have changed: different sites may have entered or left the dataset, and sampling frequency may not have remained constant.\n\nWhat the chart does show clearly is that the **typical measurement and the variability around it are two different things**. The median can remain fairly stable even during months when some observations are much higher than others.\n\n**Figure 3.** Monthly median enterococci measurements since 2000. The shaded band shows the interquartile range and highlights periods when the recorded measurements were more variable.\n\n## What I took away from this analysis\n\nI started with what seemed like a fairly simple dataset and an equally simple question: **which sites had the highest measurements?**\n\nBy the end, that was probably the least interesting question.\n\nThe April snapshot showed how easily an average can be influenced by a small number of high observations. Comparing the mean with the median and maximum made that much clearer. Looking at the data over time showed something similar: a relatively stable centre can exist alongside periods of much greater variation.\n\nThe missing values were another useful reminder. Filling an empty space with zero may make a table or heatmap easier to build, but it can also give that empty space a meaning it never had.\n\nThe biggest lesson for me was simple: before interpreting a summary statistic, I need to understand **what observations went into it**.\n\nSometimes the most useful part of an analysis is not finding the highest bar on the chart. It is figuring out why that bar is high in the first place.\n\n## Tools\n\nThis analysis was created in **R** with `tidyverse`, `lubridate`, `sf` packages, and lga 2022 map.\n\nData source: [TidyTuesday — 20 May 2025](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-05-20).\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}