<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Auggie Imuan">
<meta name="dcterms.date" content="2021-03-31">

<title>The Factors Affect CO2 Emission in 5-ASEAN Countries – Home</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d7a985b111ba49d75886cb228fa7d15a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Home</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">ABOUT</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../CV.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">The Factors Affect CO2 Emission in 5-ASEAN Countries</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">economics</div>
                <div class="quarto-category">analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Auggie Imuan </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 31, 2021</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>Global warming is driving significant changes in the climate system. The primary cause of global warming is the accumulation of greenhouse gases (GHG). A growing amount of GHG emissions can be attributed to human activities, such as industrial expansion, transportation, and other economic activities. Among these, carbon dioxide (CO2) emissions are the largest contributors to total GHG emissions (Intergovernmental Panel on Climate Change, 2014). CO2 constitutes more than 72% of global GHG emissions (Yunfeng and Laike, 2010). Furthermore, the CO2 emission share from developing countries was nearly 50 per cent of the world’s total CO2 emissions in 2003 (Martinez-Zarzoso and Maruotti, 2011).</p>
<p>A significant proportion of developing countries is represented within ASEAN, a region characterized by rapid economic development, rising income levels, and other socio-economic drivers. Increased domestic and foreign investments in ASEAN nations have led to a continuous rise in CO2 emissions, contributing to environmental degradation.</p>
<p>Although ASEAN’s CO2 emissions are lower than those of China and the USA, ASEAN is predicted to face severe consequences of global warming, including increasing sea levels (Nordin et al., 2015), which endangered coastal areas and small islands, and the severity of extreme weather events. The population in ASEAN are affected by CO2 emissions because the region is populated along coastlines and heavily reliant on agriculture for livelihoods. Rising temperatures caused by increased CO2 emissions directly affect natural resources and forestry, leading to declining rainfall, heatwaves, droughts, floods, and tropical cyclones (Environment Division of the ASEAN Secretariat, n.d.).</p>
<p>The increase in CO2 emissions in ASEAN has tended to increase occasionally. In 2018, the 5 countries in ASEAN that had the most CO2 emissions were Indonesia, Thailand, Vietnam, Malaysia, and the Philippines, respectively.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 1 can be implied that the countries top five CO2 emission in ASEAN have environmental problems. Moreover, this figure implied about what the factors that make countries top five CO2 emission in ASEAN. To achieve sustainable economic development, their countries should be taken certain step to stop or control CO2 emission (Abdul and Baserat, 2018). As Grossman and Krueger were the first to introduce the idea of the environmental Kuznets curve (EKC) hypothesis to show a negative relationship between economics growth and environmental quality (Arifur et al., 2020). And in 1971, Ehrlich and Holdren were the first introduce the idea of the analysis of key human activities that influence environmental change that is environmental impacts (I) are associated with the population (P), affluence (A), and technology (T) in ecological model called “IPAT” (Koçak et al., 2020). From 2 hypotheses, which are appropriate and can most explain factors affecting CO2 emission on the top 5 CO2 emission in ASEAN is IPAT hypothesis because IPAT theory is the effective device for operationally bridging the differing perspectives between social science and biological science (Dietz and Rosa, 1994). While the EKC ignored the impact of outside borders on the environment since the environment cannot be isolated, the IPAT model assumes the environmental impacts increase linearly with technology (Majeed and Tauqir, 2020).</p>
<p>However, this problem has not been directly studied, but studies on determinate of CO2 emission in ASEAN by using energy indicators (Nordin et al., 2015), and studies by Qaiser et al (2020) on relationship between CO2 emission, energy consumption and economic growth in 5-ASEAN (i.e.&nbsp;Indonesia, Thailand, Singapore, Malaysia, and Philippines) by using the EKC hypothesis. Therefore, this research has the objective to study applies IPAT hypothesis to explore factors affecting CO2 emission on top 5 CO2 emission in ASEAN.</p>
</section>
<section id="literature-review" class="level2">
<h2 class="anchored" data-anchor-id="literature-review">2. Literature Review</h2>
<section id="theory-of-environmental-degradation" class="level3">
<h3 class="anchored" data-anchor-id="theory-of-environmental-degradation">2.1 Theory of Environmental Degradation</h3>
<p>Nowadays, the most important problem in the world is the environmental problem. The main reason for the environmental degradation problem due to human activities. Therefore, scientists study and create theories, to explain how human activities affect the degradation of the environment. The popular theories, that describe environmental degradation, are the EKC theory and IPAT theory (Carson, 2010).</p>
<p>The&nbsp;EKC theory,&nbsp;or the environmental Kuznets curve, was&nbsp;created by Simon Smith Kuznets, an economist and statistician. This theory describes&nbsp;how&nbsp;the amount of CO2&nbsp;emissions&nbsp;will increase until the average income reaches a turning point, thus revitalizing environmental quality. Furthermore, the conventional EKC illustrates an inverted U-shaped relationship between environmental quality and economic growth/development (Grossman and Krueger, 1995).</p>
<p>On the contrary, the IPAT theory or The Environmental Impacts (I) on Population (P), Affluence (A), and Technology (T) created by Paul Ralph Ehrlich, Barry Commoner, and John Paul Holdren who are biologists, ecologists, physics and environmental scientist, respectively (York et al., 2003). The IPAT model postulates that environmental impacts increase linearly with population and affluence (York et al., 2007). Moreover, the purpose of this theory is to illustrate the population is a key driving force. It shows humans are important for driving/creating economic activities, technology, political and economic institutions, and attitudes (Stem et al., 1992).</p>
<p>In that case, the IPAT theory is better than the EKC theory, which describes reasons that affect environmental degradation. Dietz and Rosa (1997) believe IPAT theory is an effective device for operationally bridging the differing perspectives between social science and biological science. While the EKC ignored the impact of outside borders on the environment since the environment cannot be isolated, the IPAT model assumes the environmental effects increase linearly with technology (Majeed and Tauqir, 2020). Moreover, biological, ecological and other physical and environmental scientists’ models do not ignore assumptions and create dependence on actuality, while some social science will generally overlook the models (Dietz and Rosa, 1994). Mill and Waite’s (2009) studies did not support EKC’s role of affluence and population on the environment.</p>
</section>
<section id="factors-affects-to-co2-emission" class="level3">
<h3 class="anchored" data-anchor-id="factors-affects-to-co2-emission">2.2 Factors affects to CO2 emission</h3>
<p>As humans and human activities are the main reasons in the theory of environmental degradation. Even&nbsp;though&nbsp;environmental degradation cannot&nbsp;be directly&nbsp;measured, most research&nbsp;studies&nbsp;on&nbsp;environmental degradation will use CO2 emission to measure it (York et al., 2003).</p>
<p>Undoubtedly, the population is a significant reason for CO2 emissions due to the impact of the increasing population leading to the use of more energy and oil consumption even with the most managed technology (Paul and John, 1971). Moreover, Mansoor and Sultana (2018), and Guo and Yuan (2011) investigated the increasing population effect on CO2 emission, which led to environmental degradation. While increasing the population concentrated in urban centres, it began to expand urban areas (Lin et al., 2009). This made the migration of the rural population to urbanization thus using more energy and oil consumption led to environmental degradation (Yeh and Liao, 2017). Some studies such as Yeh and Liao (2017), Le et al (2020), Martinez-Zarzoso and Maruotti (2011), and Shaari et al (2020) questioned the urbanisation effect on carbon emission by using the IPAT/STIRPAT tool to analyze, found the relation of urbanization with carbon emission is positive linear.</p>
<p>On the contrary, Le and Quah (2018) and Husain (2016) questioned the urbanisation effect on carbon emission by using the EKC model to analyse and found the relation of urbanization with carbon emission is a U-shape. In other words, low levels of urbanization cause more CO2 emission while levels of urbanization reach a point that will reduce CO2 emission.</p>
<p>The other cause of CO2 emission is human activities, which can be divided into 2 types followed by IPAT theory including affluence and technology (York et al., 2003) which will mention affluence and technology, respectively. Affluence is the production/consumption of the population and affected environment, the best of indicators are income and industrial. Firstly, income can be measured by power consumption. The income illustrates the power of the consumer to afford the product, which is the cause of CO2 emission. When people can more afford the product, it leads to more production which leads to increasing CO2 emission (Guo and Jiang, 2011). In addition, Yeh and Liao (2017) and Le et al (2020) questioned the gross domestic product effect on carbon emission by using the IPAT/STIRPAT tool to analyse and found the relation of gross domestic product with carbon emission is positive linear. Some studies such as Giedre et al (2014), Le and Quah (2018), Husain (2016), Sulaiman and Abdul-Rahim (2018) and Neumayer (2002) estimated the gross domestic product effect on carbon emission by using the EKC model to analyze, found the relation of gross domestic product with carbon emission is positive as well.</p>
<p>Although most studies investigate the positive relationship between gross domestic product and carbon emission, Mansoor and Sultana (2018) investigate that GDP per capita has a negative effect on CO2 emission because GDP enables a country to reach the same production level at a low CO2 emission by development of low-carbon technology. Thus the indicator can be measured, production is industrial. Undoubtedly, CO2 emission comes from production in industry. If countries have more industry, which means increasing production, they have to use energy and oil consumption in the production process which leads to more CO2 emissions. Moreover, industrial illustrates international trade, investment, urbanization and economic growth (Le and Quah, 2018; Saboori et al., 2017). Lin et al (2009) estimated an analysis of the environmental impact of China based on the STIRPAT model. This study found the relationship between the level of industry and CO2 emission is positive, in contrast, Paramati et al (2016) examined developed economy countries that have a negative relationship between industry and CO2 emission because developed economy countries have a high level of technology to reduce CO2 emission.</p>
<p>Finally, the last cause of CO2 emission by human activities is technology. Paul and John (1971) believe that in a technological society, each human individual has a negative impact on the environment. Even though, technology is an indicator that difficult measures to value, most researchers use energy consumption to describe the level of technology, for example, if less energy consumption refers to the level of technology is high (Mansoor and Sultana, 2018). Zhang and Chenh (2009) examined how an increase in energy consumption brings about an increased CO2 emission. In addition, the indicators that use rather energy consumption is energy intensity (Koçak et al., 2020). Wolde-Rufael and Idowu (2017) investigated that China and India have a positive relationship between energy consumption and CO2 emission due to low-level technology. Thus it used high energy intensity in contrast low energy intensity implied the high level of technology. Talbi (2017) and Le et al (2020) express energy consumption illustrate technology, moreover; energy consumption measured by energy intensity investigated energy intensity positive effects on CO2 emission in the short run. On the contrary, Koçak et al (2020) and Xu and Ang (2013) found the reduction in energy intensity represents technological development, which is the key driving force for reducing emissions, and found energy intensity has a negative relationship with CO2 emission.</p>
</section>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">3.Methodology</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">3.1 Data</h3>
<p>This research taking account of data availability, the panel data of 5 countries in ASEAN (i.e., Thailand, Indonesia, Vietnam, Malaysia, and Philippines) over period 1990-2015 are used to study. The data of <code>CO2 emission (kt)</code>, <code>Gross Domestic Product per capita (constant 2015 US$)</code>, <code>Industry value added per capita (constant 2015 US$)</code>, <code>Population (total)</code>, <code>Urban population (% of total population)</code>, and <code>Energy intensity level of primary energy (MJ/$2017 PPP GDP)</code> of Thailand, Indonesia, Vietnam, Malaysia, and Philippines were obtained from <a href="https://databank.worldbank.org/home">World Bank</a>.</p>
</section>
<section id="methodology-1" class="level3">
<h3 class="anchored" data-anchor-id="methodology-1">3.2 Methodology</h3>
<section id="theoretical-model" class="level4">
<h4 class="anchored" data-anchor-id="theoretical-model">3.2.1 Theoretical Model</h4>
<p>In this section, the research has an objective to study the factors affect to CO2 emission in Thailand, Indonesia, Vietnam, Malaysia, and Philippines. By used theories concerned about environmental degradation called “IPAT”. This theory focuses on key human activities that influence environmental change that can help to explain the objective of research.</p>
<p>However, the analysis of key human activities that influence environmental change by IPAT (Ehrlich and Holdren, 1971) is the model was purely a concept and cannot be used directly in empirical research (Chen et al., 2020). This research used the theory developed from IPAT for describe by mathematic, called the STIRPAT (Stochastic Impacts by Regression on Population, Affluence, and Technology) model (Dietz and Rosa, 1997) to study combined use to be analyzed with econometric models by fixed effect method. For studying the relationship of factors to CO2 emission in Thailand, Indonesia, Vietnam, Malaysia, and Philippines. The basic model is written follow:</p>
<p><span class="math display">\[I=f(P,A,T)\tag{1}\]</span></p>
<p>By specify where I represent the environmental impact, P represents population, A represents affluence, and T represents technology. This research modifies appropriate for objective of study which can be expressed as:</p>
<p>I is the environmental impact or environmental degradation, measured by CO2 emission (CO2) because it constitutes the largest share of environmental degradation (Shaari et al., 2020).</p>
<p>P is population which it can measure by total population and urbanization. In other word, total population (POP) and urbanization (URB) increase lead to an increased competition for environmental resources which lead to environmental degradation (Dietz and Rosa, 1997). While total population can be measured by total population, urbanization can be measured by urban population.</p>
<p>A is affluence. This research chooses variables by literature review for factors affecting CO2 emission, measured by income and industrial. In other words, affluence is a convenient abbreviation for consumption patterns and some measure of income as the indicator of affluence (Dietz and Rosa, 1997). Income can be proxy by gross domestic product per capita (GDP) because it is the usual measure of economic activity in IPAT models moreover, the relation environmental degradation depends on income increase (World bank, 1992). Additionally, Industrial can illustrate affluence due to it shows terms of trade, export, import, stocks and in terms of production (Fischer-Kowalski et al., 2011). Undoubtedly, industrial can be proxy by industrial value added (IND) due to economic growth will increase energy demand, rising urbanization and industrialization will increase CO2 emission (Le and Quah, 2018; Saboori et al., 2017).</p>
<p>T is technology. Technology in this research chooses variables by literature review for factors affecting CO2 emission, which can be measured by energy intensity (ENE). In simple terms, if use less energy intensity that show technological development (Koçak et al., 2020). Additionally, energy intensity can be measured by energy intensity level of primary energy. If increased energy intensity level of primary energy, increases emissions due to global warming (Jones, 1991). From above mention, function of study can be expressed as:</p>
<p><span class="math display">\[CO2=f(POP,URB,GDP,IND,ENE)\tag{2} \]</span><br>
<span class="math display">\[CO2= POP^{\beta_1} URB^{\beta_1} GDP^{\beta_3} IND^{\beta_4} ENE^{\beta_5} \tag{3}    \]</span><br>
This study predicts, population has a positive effect on CO2 emission (Anwar et al., 2020). Moreover, prediction of urbanization is positive effects on CO2 emission (Martinez-Zarzoso and Maruotti, 2011). Furthermore, prediction of GDP per capita and industry value added are a positive effect on CO2 emission (Le et al., 2020). Lastly, prediction of energy intensity is positive effect on CO2 emission (Cole and Neumayer, 2004).</p>
<p>Equation that modifies explains the factors that affect CO2 emission in 5-ASEAN countries (i.e., Thailand, Indonesia, Vietnam, Malaysia, and Philippines). The variables in the Equation 3 are converted into logarithmic form because the STIRPAT model has to use logarithmic (Dietz and Rosa, 1997). as follows:</p>
<p><span class="math display">\[
\ln CO_{2_{it}} = \beta_0 + \beta_1 \ln POP_{it} + \beta_2 \ln URB_{it} + \beta_3 \ln GDP_{it} + \beta_4 \ln IND_{it} + \beta_5 \ln ENE_{it} + \varepsilon_{it} \tag{4}
\]</span></p>
<p>By specifying where <span class="math inline">\(CO_{2_{it}}\)</span> represent CO2 emission of Thailand, Indonesia, Vietnam, Malaysia, and Philippines in year t, <span class="math inline">\(POP_{it}\)</span> represent population of Thailand, Indonesia, Vietnam, Malaysia, and Philippines in year t, <span class="math inline">\(URB_{it}\)</span> represent the urban population of Thailand, Indonesia, Vietnam, Malaysia, and Philippines in year t, <span class="math inline">\(GDP_{it}\)</span> represent gross domestic product of Thailand, Indonesia, Vietnam, Malaysia, and Philippines in year t, <span class="math inline">\(IND_{it}\)</span> represent industrial value added of Thailand, Indonesia, Vietnam, Malaysia, and Philippines in year t, and <span class="math inline">\(ENE_{it}\)</span> represents energy intensity of Thailand, Indonesia, Vietnam, Malaysia, and Philippines in year t. <span class="math inline">\(\beta_0\)</span> represents a constant term, 1,2,3,4,5 are the estimated parameters, and <span class="math inline">\(\varepsilon_{it}\)</span> is the error term in year t. i is the 5 countries in ASEAN (i.e., Thailand, Indonesia, Vietnam, Malaysia, and Philippines). where t is time (t = 1,2,3,…,26) use panel data. Estimated the equation by using Ridge Regression because predictors are strong correlation consequently, ridge regression is suitable for this issue.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlation Matrix of Predictors</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">ln_ene</th>
<th style="text-align: right;">ln_gdp</th>
<th style="text-align: right;">ln_pop</th>
<th style="text-align: right;">ln_urb</th>
<th style="text-align: right;">ln_ind</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ln_ene</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.0123012</td>
<td style="text-align: right;">-0.4461180</td>
<td style="text-align: right;">0.2835165</td>
<td style="text-align: right;">0.1712007</td>
</tr>
<tr class="even">
<td style="text-align: left;">ln_gdp</td>
<td style="text-align: right;">-0.0123012</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.5971792</td>
<td style="text-align: right;">0.3357580</td>
<td style="text-align: right;">0.9690089</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ln_pop</td>
<td style="text-align: right;">-0.4461180</td>
<td style="text-align: right;">0.5971792</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.3699070</td>
<td style="text-align: right;">0.5120299</td>
</tr>
<tr class="even">
<td style="text-align: left;">ln_urb</td>
<td style="text-align: right;">0.2835165</td>
<td style="text-align: right;">0.3357580</td>
<td style="text-align: right;">-0.3699070</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.3965863</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ln_ind</td>
<td style="text-align: right;">0.1712007</td>
<td style="text-align: right;">0.9690089</td>
<td style="text-align: right;">0.5120299</td>
<td style="text-align: right;">0.3965863</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This matrix shows ln_gdp and ln_ind have a very strong correlation (<span class="math inline">\(r = 0.969\)</span>), this indicates severe multicollinearity. While the other correlations are not as high as <span class="math inline">\(r &gt; 0.8\)</span> , there are some moderate relationships.</p>
</section>
</section>
</section>
<section id="description-and-discussion-of-the-results" class="level2">
<h2 class="anchored" data-anchor-id="description-and-discussion-of-the-results">4. Description and discussion of the results</h2>
<p>The result from study the factors affect the CO2 emission in 5-ASEAN countries. Expressed as analysis results.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Ridge Regression Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-5032.847912</td>
</tr>
<tr class="even">
<td style="text-align: left;">ln_ene</td>
<td style="text-align: right;">107.617964</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ln_gdp</td>
<td style="text-align: right;">75.802601</td>
</tr>
<tr class="even">
<td style="text-align: left;">ln_pop</td>
<td style="text-align: right;">22.656423</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ln_urb</td>
<td style="text-align: right;">-3.369899</td>
</tr>
<tr class="even">
<td style="text-align: left;">ln_ind</td>
<td style="text-align: right;">106.214714</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The Ridge Regression model explains approximately $ R^2 = 0.932 $ of the variance in the dependent variable.</p>
<p>The Ridge Regression model equation is expressed as follows:</p>
<p><span class="math display">\[
\ln(y) = -5032.85 + 107.62 \cdot \ln(ene) + 75.80 \cdot \ln(gdp) + 22.66 \cdot \ln(pop) - 3.37 \cdot \ln(urb) + 106.21 \cdot \ln(ind)
\]</span></p>
<p>The table illustrates the result regression of factors that affect CO2 emission in 5-ASEAN countries, including Thailand, Indonesia, Vietnam, Malaysia, and Philippines by 5 factors.</p>
<p>Overall, R-squares within is 0.9324 in other words, all factors can describe CO2 emission with 93.24% by ridge regression while 6.76% explained by other factors.</p>
<p>From the result, it can be seen that population has a positive effect on CO2 emission refer to when population increases 1 percent, will be CO2 emission increases 22.66 percent. This result matches the hypothesis, the relation of population with carbon emission is positive. Moreover, the result consist study with Mansoor and Sultana (2018) question Impact of Population, GDP and Energy Consumption on Carbon Emissions: Evidence from Pakistan Using an Analytic Tool IPAT, examined the impact of population on CO2 emissions is positive, which confirmed that high population growth put a burden on environment in the form of high mass CO2 emissions, hence this study suggests limiting the population by family planning process in a country. Furthermore, Guo and Yuan (2011) questioned the relationship between CO2 Emissions, Economic Scale, Technology, Income and Population in China by using the IPAT model to analyze, found the population is positive relation with CO2 emission.</p>
<p>Urbanization has a negative effect on CO2 emission that is urbanization increases 1 percent, will be CO2 emission reduce -3.37 percent. This result does not match the hypothesis, the relation of urbanization with carbon emission is positive. The result of study conflict with Yeh and Liao (2017), Le et al (2020), Martinez-Zarzoso and Maruotti (2011), and Shaari et al (2020) questioned the urbanization effect to carbon emission by using IPAT/STIRPAT tool to analyze, found the relation of urbanization with carbon emission is positive linear due to expansion of urbanization led to use more natural resource. Although, this result does not match hypothesis and other studies result, Martinez-Zarzoso and Maruotti (2011) found the same problem, urbanization is negative relation with carbon emission then this study used more sophisticated analysis to investigate this relationship in depth, investigated a relationship between urbanization and CO2 emission is U-shaped thus this study suggests the problem are the data of urbanization in countries that studied do not appropriate with the IPAT model but appropriate with the EKC model. In conclusion, this reason might the cause studies to have different results.</p>
<p>Gross domestic product has a positive effect on CO2 emission means when gross domestic product increases 1 percent, will be CO2 emission increase 75.80 percent. This result matches the hypothesis, the relation of gross domestic product with carbon emission is positive. Moreover, the result consist study with Yeh and Liao (2017) and Le et al (2020) questioned gross domestic product impact to carbon emission by using IPAT/STIRPAT tool to analyze, found the relation of gross domestic product with carbon emission is positive relation. While Giedre et al (2014), Le and Quah (2018), Husain (2016), and Neumayer (2002) investigate the positive relationship between GDP and carbon emission by using EKC model as well. On the contrary, Mansoor and Sultana (2018) investigate GDP per capita has negative affect on CO2 emission due to GDP enable country to reach the same production level at low CO2 emission by development of low-carbon technology. While this study focuses on 5-ASEAN countries by using panel data and using fixed effects to analyze, Mansoor and Sultana (2018) study focus on Pakistan by using time-serie data and use ARDL to analyze relation in long-run. In summary, this reason causes studies to have different results.</p>
<p>Industrial value added has a positive effect on CO2 emission consists of when industrial value added increases 1 percent, will be CO2 emission increase 106.21 percent. This result matches the hypothesis, the relation of industrial value added with carbon emission is positive. Moreover, the result consists of study with Le et al (2020) surveyed industry has positive relation with CO2 emission. Although, Paramati et al (2016) examined developed economy countries that have negative relationships between industry and CO2 emission, developing economy countries have positive relationships based on the STIRPAT model. This is the reason to relates with the result of study due to 5-ASEAN countries such as Thailand, Indonesia, Vietnam, Malaysia, and Philippines are developing countries.</p>
<p>Energy intensity has a positive effect on CO2 emission consists of when energy intensity increases 1 percent, will be CO2 emission increase 107.62 percent. This result matches the hypothesis, the relation of energy intensity with carbon emission is positive. Moreover, the result consist study with Talbi (2017) sounded energy consumption illustrate technology, moreover energy consumption measured by energy intensity, investigated energy intensity positive effects with CO2 emission in short run. Moreover, Le et al (2020) examined energy intensity has positive relation with CO2 emission. On the contrary, Koçak et al (2020) sounded the reduction in energy intensity represent technological development, found energy intensity has a negative relationship with CO2 emission. While, this study focuses on 5-ASEAN countries, Koçak et al (2020) study focus on top 10 most visited countries in 2017 which is most developed countries. Moreover, developed countries have high technology to use less energy intensity consist study with Bilgili et al (2017) examined decreasing of energy intensity due to developed technology. To sum up, this reason causes studies to have different results.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">5. Conclusion</h2>
<p>The purpose of this study is factors affect CO2 emission in 5-ASEAN countries. From the result, the causes of CO2 emission in 5-ASEAN countries are population, urbanization, gross domestic product, industry, and energy intensity, affected to CO2 emission by the same direction while urbanization contrarily affects CO2 emission. Moreover, the results of this study illustrate the IPAT hypothesis, which can examine causes of environmental degradation to reflect environmental sustainability.</p>
<p>The results suggest total factors affect CO2 emission. Although, the most factor effect CO2 emission is population, nobody can control about having children due to external factors that cannot control human thoughts and decisions. As the result, the government should dramatically support R&amp;D of technology to develop technology for less CO2 emission due to developed technology can solve CO2 emission from GDP per capita and industrial. Furthermore, the government should announce the policy concerning carbon emission such as environmental tax for controlling the industries to cooperate with the government for use of low-carbon technology to reduce carbon emission.</p>
<p>Suggestions for future research are using the IPAT model to analyze. Be careful the data of urbanization to analyze due to the relationship is maybe non-linear and the IPAT model has a problem about autocorrelation from theory thus the future research should find the way to solve this problem.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Asean Cooperation on Environment. (n.d.). ASEAN Cooperation on Climate Change. Environment Division of the ASEAN Secretariat. Retrieved from https://environment.asean.org/awgcc/</p>
<p>Bilgili, F., Koçak, E., Bulut, Ü., &amp; Kuloğlu, A. (2017). The impact of urbanization on energy intensity: Panel data evidence considering cross-sectional dependence and heterogeneity. Energy, 133, 242-256.</p>
<p>Carson, R. T. (2010). The Environmental Kuznets Curve: Seeking Empirical Regularity and Theoretical Structure. Review of Environmental Economics and Policy, 4(1).</p>
<p>Chen, Y., Lee, C., &amp; Lee, C. (2020). Does technological innovation reduce CO2 emission?Cross-country evidence. Journal of Cleaner Production, 263, 121550.</p>
<p>Cole, M. A., &amp; Neumayer, E. (2004). Examining the Impact of Demographic Factors on Air Pollution. Population and Environment, 26(1), 5–21.</p>
<p>Dietz, T. &amp; Rosa, E. A. (1994). Rethinking the Environmental Impacts of Population, Affluence and Technology, Human Ecology Review, 1, 277-300.</p>
<p>Dietz, T. &amp; Rosa, E. A. (1997). Effect of population and affluence on CO2 emission, Ecology, 94, 175-179.</p>
<p>Dietz, T. &amp; Rosa, E. A. (2007). Driving the human ecological footprint. Frontiers in Ecology and the Environment, 5(1), 13-18.</p>
<p>Fischer-Kowalski, M., Krausmann, F., Giljum, S., Lutter, S., Mayer, A., Bringezu, S., … Weisz, H. (2011). Methodology and Indicators of Economy-wide Material Flow Accounting. Journal of Industrial Ecology, 15(6), 855-876.</p>
<p>Giedre, L., Manuela, T. &amp; Pranas, V. (2014). Greenhouse gases emissions and economic growth - evidence substantiating the presence of environmental Kuznets curve in the EU. Technological and Economic Development of Economy, 20(1), 65-78.</p>
<p>Grossman, G. M. &amp; Krueger, A. (1995). Economic Growth and the Environment. The Quarterly Journal of Economics, 11(2), 353-377.</p>
<p>Guo, H. &amp; Jiang, Y. (2011). The Relationship between CO2 emissions, Economic Scale, Technology, Income and Population in China. Procedia Environmental Sciences, 11, 1183-1188.</p>
<p>Husain, S. (2016). Testing the long run relationship between CO2 emission, Energy consumption and Economics Growth for Bangladesh. An ARDL Bound Testing Approach. British Journal of Economics, Finance and Management Sciences, 12(2), 12-23.</p>
<p>Inmaculada, M., Inmaculada, Z. &amp; Antonello M. (2011). The impact of urbanization on CO2 emissions: Evidence from developing countries. Ecological Economics, 70, 1344-1353.</p>
<p>Intergovernmental Panel on Climate Change. (2014) Climate Change 2014 Mitigation of Climate Change. New York, Cambridge University Press. Jones, D. W. (1991). How urbanization affects energy-use in developing countries. Energy Policy, 19(7), 621-630. Koçak, E., Ulucak, R., &amp; Ulucak, Z. Ş. (2020). The impact of tourism developments on CO2 emission: An advanced panel data estimation. Tourism Management Perspectives, 33, 100611.</p>
<p>Le, T.-H., Le, H.-C., &amp; Taghizadeh-Hesary, F. (2020). Does financial inclusion impact CO2 emission? Evidence from Asia. Finance Research Letters, 34, 10145.</p>
<p>Le, T. &amp; Quah, E. (2018). Income level and the emission, energy, and growth nexus: Evidence from Asia and the Pacific. International Economics, 156, 193-205.</p>
<p>Lin, S., Zhao, D. &amp; Marinova, A. (2009). Analysis of the environmental impact of China based on STIRPAT model. Environmental Impact Assessment Review, 29, 341-347.</p>
<p>Luukkanen, J. &amp; Kaivo-oja, J. (2002). ASEAN tigers and sustainability of energy use-decomposition analysis of energy and CO2 efficiency dynamics. Energy Policy, 30(4), 281-292</p>
<p>Majeed, M. T. &amp; Tauqir, A. (2020). Effects of Urbanization, Industrialization, Economic Growth, Energy Consumption and Financial Development on Carbon Emission: An Extended STIRPAT Model for Heterogenous Income Groups. Pakistan Journal of Commerce and Social Sciences, 14(3), 652-681.</p>
<p>Mansoor, A. &amp; Sultana, B. (2018). Impact of Population, GDP and Energy Consumption on Carbon Emission: Evidence from Pakistan Using and Analytic Tool IPAT. Asian Journal of Economics and Empirical Research, 5(2), 183-190.</p>
<p>Martínez-Zarzoso, I., &amp; Maruotti, A. (2011). The impact of urbanization on CO2 emissions: Evidence from developing countries. Ecological Economics, 70(7), 1344-1353.</p>
<p>Meangbua, O., Dhakal, S., &amp; Kuwornu, J. K. M. (2019). Factors influencing energy requirements and CO2 emissions of households in Thailand: A panel data analysis. Energy Policy, 129, 521–531.</p>
<p>Mills, J.H., &amp; Wate, T. A. (2009). Economic prosperity, biodiversity conservation, and the environmental Kuznets curve. Ecological Economics, 68(7), 2087-2095.</p>
<p>Munir, Q., Lean, H. H., Smyth, R. (2020). Co2 emissions, energy consumption and economic growth in the ASEAN-5 countries: A cross-sectional dependence approach. Energy Economics, 85, 104571.</p>
<p>Neumayer, E. (2002). Can natural factors explain any cross-country difference in carbon dioxide emissions?. Energy Policy, 30, 7-12.</p>
<p>Nordin, S. K. S., Samat, K. F., Ismail, S. F., Hamzah, K., Halim, B. A., &amp; Kun, S. S. (2015). Determinants of CO2 emissions in ASEAN countries using energy and mining indicators. AIP Conference Proceeding, 1660(1).</p>
<p>Paramati, S. R., Alam, Md. S. &amp; Chen, C. (2016). The Effects of Tourism on Economic Growth and CO2 Emission: A Comparison between Developed and Developing Economies. Journal of Travel Research, 56(6), 712-724.</p>
<p>Pual, R. E. &amp; John, P.H. (1971). Impact of Population Growth. Science, 171(3977), 1212-1217.</p>
<p>Rabiul, I., Ahmad, B. A. G., &amp; Emil, M. (2017). Carbon Dioxide Emission, Energy Consumption, Economic Growth, Population, Poverty and Forest Area: Evidence from Panel Data Analysis. International Journal of Energy Economics and Policy, 7(4), 99-106.</p>
<p>Rahman, A., Murad, S. M. W., Ahmad, F., &amp; Wang, X. (2020). Evaluating the EKC Hypothesis for the BCIM-EC Member Countries under the Belt and Road Initiative. Sustainability, 12(4), 1478.</p>
<p>Saboori, B., Rasoulinezhad, E., &amp; Sung, J. (2017). The nexus of oil consumption, CO2 emissions and economic growth in China, Japan and South Korea. Environmental Science and Pollution Research, 24(8), 7436-7455.</p>
<p>Shaari, M. S., Karim, Z. A., &amp; Abidin, N. Z. (2020). The effects of Energy Consumption and National Output on CO2 emissions: New Evidence from OIC Countries Using a Panel ARDL Analysis. sustainability, 12, 3312.</p>
<p>Shafik, N. (1994). Economic Development And Environmental Quality: An Econometric Analysis. Oxford Economic Paper, 46, 757-773.</p>
<p>Stern, D. I. (2004). The rise and fall of the environmental Kuznets curve. World Development, 32, 1419-1439.</p>
<p>Stern, P. C. (1993). A Second Environmental Science: Human-Environment Interactions. Science, 260(5116), 1897-1899.</p>
<p>Sulaiman, C. &amp; Abdul-Rahim, A. S. (2018). Population Growth and CO2 emission in Nigeria: A Recursive ARDL Approach. SAGE Open, 8(2), 215824401876591.</p>
<p>Talbi, B. (2017). CO2 emission reduction in road transport sector in Tunisia. Renewable and Sustainable Energy Reviews, 69, 232-238.</p>
<p>The Global Carbon Atlas. CO2 emission in ASEAN during 1960 to 2018. Retrieved from http://www.globalcarbonatlas.org/en/CO2-emissions</p>
<p>Wolde-Rufael, Y. &amp; Idowu, S. (2017). Income distribution and CO2 emission: A comparative analysis for China and India. Renewable and Sustainable Energy Reviews, 74, 1336-1345.</p>
<p>World Bank Indicators. (1992). World Development Report Development and the Environment. World Bank. Retrieved from http://documents1.worldbank.org/curated/en/995041468 323374213/pdf/105170REPLACEMENT0WDR01992.pdf</p>
<p>Xu, X. Y. &amp; Ang, B. W. (2013). Index decomposition analysis applied to CO2 emission studies. Ecological Economics, 93, 313-329.</p>
<p>Yeh, J. &amp; L, C. (2017). Impact of population and economic growth on carbon emission in Taiwan using and analytic tool STIRPAT. Sustainable Environment Research, 27, 41-48.</p>
<p>York, R., Rosa, E. A., &amp; Dietz, T. (2003). STIRPAT, IPAT and ImPACT: analytic tools for unpacking the driving forces of environmental impacts. Ecological Economics, 46, 351-365.</p>
<p>Zhang, X. &amp; Cheng, X. (2009). Energy consumption, carbon emission, and economic growth in China. Ecological Economics, 68, 2706-2712.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/aphiaut\.github\.io\/myblog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>